### ISSUE TITLE
Upload stalls when attempting to upload function from a newly loaded segment

### ISSUE THREAD

**Issue by cmarczewski** [vrtadmin/FIRST-plugin-ida#12]
More specifically, this function resides in a segment that was loaded during a debug session. It is not derived from one of the original PE sections (.text, etc.)

I marked it as a loader segment so I could take memory snapshots that did not include all segments. Steps taken to try & upload the function:

1. Create the function in question, in IDA.
2. After debugging, take one last memory snapshot.
3. Save the IDB.
4. Terminate.
5. Attempt to upload the function to the public server.

The dialog box is populated as expected, but it stalls at 0% progress. I've provided the IDB to the plugin author via e-mail.

**Comment by cmarczewski** [comment]
Also worth mentioning that the input file for this IDB did not come from disk. I attached IDA Pro to a suspended child process that originated from the sample on disk & broke on RtlUserThreadStart until execution resumed as expected.

**Comment by demonduck** [comment]
It seems this issue is occurring due to the way the sample was obtained. FIRST leverages IDA's API to get the MD5 and CRC32 values from a sample to store the function. The way you obtained the code caused IDA to have no original file, thus no MD5 or CRC32 data. Without that FIRST will not operate correctly. The commit above fixes this issue, or at least handles it gracefully. 

The issue can be circumvented by assigning an MD5 and CRC32 to FIRST. For this I added the function `FIRST.Info.set_file_details`. Simply call the function form IDA's `Output Window` (set to Python) and then attempt uploading the function again. This function contains optional arguments for the sample sha1 and sha256 too (see `help(FIRST.Info.set_file_details)`).

```python
FIRST.Info.set_file_details(<MD5>, <CRC32>)
```

Setting issue to closed. Please reopen if you experience additional bugs/issues with the fix
